flake8 silently fails due to upstream flake8_docstrings bug
Problem: Running flake8 in this repo currently does not actually check
flake8 conformance but instead crashes with some output (but exits 0):

    Process Process-11:
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
        self.run()
      File "/usr/local/lib/python2.7/multiprocessing/process.py", line 114, in run
        self._target(*self._args, **self._kwargs)
      File "/usr/local/lib/python2.7/site-packages/flake8/checker.py", line 666, in _run_checks_from_queue
        checker.run_checks(results_queue, statistics_queue)
      File "/usr/local/lib/python2.7/site-packages/flake8/checker.py", line 606, in run_checks
        self.run_ast_checks()
      File "/usr/local/lib/python2.7/site-packages/flake8/checker.py", line 510, in run_ast_checks
        checker = self.run_check(plugin, tree=ast)
      File "/usr/local/lib/python2.7/site-packages/flake8/checker.py", line 464, in run_check
        return plugin['plugin'](**arguments)
      File "/usr/local/lib/python2.7/site-packages/flake8_docstrings.py", line 50, in __init__
        self.checker = pep257.PEP257Checker()
    AttributeError: 'module' object has no attribute 'PEP257Checker'

This is a known bug in flake8_docstrings:
  https://gitlab.com/pycqa/flake8-docstrings/issues/19

Analysis: Until the bug is fixed, disable flake8_docstrings checks.
Also fix the flake8 bug that I just introduced (that was hidden by the
flake8-returns-0 issue).